### ISSUE TITLE
ADO Task: Error: Crawl base URL should not have any query parameters

### ISSUE THREAD

**Issue by damongr-msft** [microsoft/accessibility-insights-action#1332]
## Describe the bug

Our web site under test requires a valid query string to operate (otherwise it will error). Having this limitation makes it so the ADO task is unusable for our scenario.

**To Reproduce**
Steps to reproduce the behavior: Below is the yaml used to test, see the url with query strings

task: accessibility-insights@3
            displayName: Scan for accessibility issues
            inputs:
              hostingMode: 'dynamicSite'
              url: 'https://ourapp.contoso.com/?appid=1235&area=test' 
              serviceAccountName: $(serviceAccountName) # Key vault secret name for the service account name
              serviceAccountPassword: $(serviceAccountPassword) # Key vault secret name for the service password
              authType: 'AAD'
              singleWorker: true
              uploadOutputArtifact: true         

## CodePen repro example

The above yaml outputs the error:
##[error][Exception]ErrorWithCause: An error occurred while scanning website page https://ourapp.contoso/?appid=1235&area=test
    at Logger.trackExceptionAny (D:\a\_tasks\accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113\3.1.0\index.js:189142:29)
    at Scanner.<anonymous> (D:\a\_tasks\accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113\3.1.0\index.js:190329:29)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_tasks\accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113\3.1.0\index.js:190244:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
caused by: Error: Crawl base URL should not have any query parameters. https://ourapp.contoso/?appid=1235&area=test

## Expected behavior

Expected to run against the web site as it requires query parameters to run properly

## Context (please complete the following information)
N/A

## Are you willing to submit a PR?

Maybe

## Did you search for similar existing issues?
Yes

**Comment by brocktaylor7** [comment]
Hello @damongr-msft,
Due to a limitation of an upstream library from us, unfortunately you can't have a query parameter in the `url` input. There is a workaround that is a bit quirky but is better than nothing. Here's how to implement the workaround:

1. Specify URLs with query parameters using the `inputUrls` input
2. Set the `url` input to the URL excluding the query parameter
3. Set the `maxUrls` input to the same number of URLs specified in the `inputUrls` input.

During execution, the `inputUrls` are added to the processing queue first, so it will process the URLs with the query parameter and will stop scanning before it adds the main `url` without the query parameter to the queue.  The downside is that you can't properly crawl any URLs using a query parameter.

We're still looking into the feasibility of changing this in the upstream package that causes this behavior, but don't currently have a timeline for when this might be fully resolved.

**Comment by DaveTryon** [comment]
There's nothing that we can do with this at the moment
