### ISSUE TITLE
Error: "pQuerySelectorAll is not a function"

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-action#1713]
## Describe the bug

A customer has reported that version 3.4.0 of the ADO Extension is failing with the following (redacted) log:
```
Starting: Scan for accessibility issues in Canary
==============================================================================
Task         : Accessibility Insights Azure DevOps Task
Description  : Scan for accessibility issues in an Azure DevOps pipeline
Version      : 3.4.0
Author       : Accessibility Insights
Help         : For help with configuring and troubleshooting this task, see https://aka.ms/accessibility-insights-faq#azure-devops-extension
==============================================================================
Installing runtime dependencies
##[debug][Telemetry] tracking a 'ScanStart' event
##[debug][Telemetry] tracking a 'Inputs' event
##[debug][Telemetry] tracking a 'AuthUsed' event
Scanning URL [REDACTED]
##[debug]Starting accessibility scanning of URL [REDACTED]
##[debug]Chrome app executable: /usr/bin/google-chrome
##[debug] Created a data storage folder at /home/vsts/work/_temp/accessibility-insights-action-bj4suj. You can override the path by setting the APIFY_LOCAL_STORAGE_DIR environment variable
##[debug] PuppeteerCrawler:AutoscaledPool:Snapshotter: Setting max memory of this run to 1736 MB. Use the APIFY_MEMORY_MBYTES environment variable to override it.
##[debug] PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
##[debug]KMSI page handled.
##[debug]Authentication succeeded.
Processing [REDACTED]
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"[REDACTED","retryCount":1,"id":"EpDaKLo3wIzVW6z"}](REDACTED%22,%22retryCount%22:1,%22id%22:%22EpDaKLo3wIzVW6z%22})
  Error: Evaluation failed: TypeError: pQuerySelectorAll is not a function
      at pptr://__puppeteer_evaluation_script__:2:12
      at ExecutionContext._ExecutionContext_evaluate (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async CDPJSHandle.evaluateHandle (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:65:16)
      at async Function.queryAll (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:73:24)
      at async Function.collect (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/util/AsyncIterableUtil.js:20:26)
      at async CDPElementHandle.$$eval (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js:115:25)
      at async ClassicPageProcessor.enqueueLinks [as enqueueLinksExt] (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/apify/build/enqueue_links/enqueue_links.js:112:25)
      at async ClassicPageProcessor.enqueueLinks (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/accessibility-insights-scan/dist/index.js:4425:26)
      at async ClassicPageProcessor.processPage (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.4.0/node_modules/accessibility-insights-scan/dist/index.js:4263:13)
```

I have the full logs and links to the original pipeline, but I'm not including them here for privacy reasons.

There are no problems if release 3.3.0 is used. Looking at the code, `pQuerySelectorAll` was not part of the version of `puppeteer` that we used in version 3.3.0.

**Comment by DaveTryon** [comment]
This has been fixed in release 3.6.0.
