### ISSUE TITLE
TypeError: Cannot read property 'baseUrl' of undefined

### ISSUE THREAD

**Issue by ashwinGokhale** [microsoft/accessibility-insights-action#2014]
## Describe the bug

Null pointer exception when reading scan results:

##[error][Exception]ErrorWithCause: An error occurred while scanning website page http://localhost:9009/
    at Logger.trackExceptionAny (/__w/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/2.0.6/index.js:189664:29)
    at Scanner.<anonymous> (/__w/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/2.0.6/index.js:190823:29)
    at Generator.next (<anonymous>)
    at fulfilled (/__w/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/2.0.6/index.js:190741:58)
caused by: TypeError: Cannot read property 'baseUrl' of undefined
    at Scanner.getCombinedReportParameters (/__w/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/2.0.6/index.js:190837:60)
    at Scanner.<anonymous> (/__w/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/2.0.6/index.js:190815:55)
    at Generator.next (<anonymous>)
    at fulfilled (/__w/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/2.0.6/index.js:190741:58)
Accessibility scanning of URL http://localhost:9009/ completed

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

The task should succeed.

## Context (please complete the following information)

- OS Name & Version: 
- Azure DevOps Extension Version & Environment:  v2.0.6. Linux Ubuntu 20.04
- Browser Version: 
- Target Page: 

## Are you willing to submit a PR?

Yes

**Comment by v-viyada** [comment]
The issue is specific to v2.0. Please use the latest version. Also ADO Extension currently does not support on Linux containers which is tracked [#1575](https://github.com/microsoft/accessibility-insights-action/issues/1575)
